import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { parse, stringify } from 'yaml'
import type { McpServerConfig, RuleFile } from '@dhd/shared'
import { mcpConfigPath, resolveDshHome } from './paths.ts'

interface McpFile {
  servers: McpServerConfig[]
}

export function loadMcp(): McpServerConfig[] {
  try {
    const raw = parse(readFileSync(mcpConfigPath(), 'utf8')) as McpFile
    return Array.isArray(raw?.servers) ? raw.servers : []
  } catch {
    return []
  }
}

export function saveMcp(servers: McpServerConfig[]): void {
  const file = mcpConfigPath()
  mkdirSync(dirname(file), { recursive: true })
  writeFileSync(file, stringify({ servers }), 'utf8')
  writeHarnessOverlay(servers)
}

export function desktopMcpPatchPath(): string {
  return join(resolveDshHome(), 'desktop-mcp.patch.yml')
}

function writeHarnessOverlay(servers: McpServerConfig[]): void {
  const dest = desktopMcpPatchPath()
  const enabled = servers.filter((s) => !s.disabled)
  const rows = enabled.map((server) => {
    if (server.transport === 'streamable-http' && server.url) {
      return {
        id: `mcp-${server.id}`,
        name: '@deepseek-ai/dsh-mcp-client',
        config: {
          servers: {
            [server.id]: { transport: 'streamable-http', url: server.url },
          },
        },
      }
    }
    return {
      id: `mcp-${server.id}`,
      name: '@deepseek-ai/dsh-mcp-client',
      config: {
        servers: {
          [server.id]: {
            transport: 'stdio',
            command: server.command,
            args: server.args,
            env: server.env,
          },
        },
      },
    }
  })
  const header = [
    '# Generated by DeepSeek Harness Desktop MCP panel. Passed as --patch, not the user home overlay.',
    '',
  ].join('\n')
  const body = rows.length === 0 ? '# (no MCP servers enabled)\n' : stringify(rows)
  if (!existsSync(dirname(dest))) mkdirSync(dirname(dest), { recursive: true })
  writeFileSync(dest, `${header}${body}`, 'utf8')
}

const RULE_NAMES = new Set(['AGENTS.md', 'agents.md', 'CLAUDE.md', 'README.md'])

export async function listRuleFiles(projectPath: string): Promise<RuleFile[]> {
  const { readdir } = await import('node:fs/promises')
  const found: RuleFile[] = []

  async function consider(dir: string, kind: RuleFile['kind']) {
    try {
      const entries = await readdir(dir, { withFileTypes: true })
      for (const entry of entries) {
        if (entry.isDirectory()) {
          if (kind === 'skill' || kind === 'dsh-skill') {
            const readme = join(dir, entry.name, 'SKILL.md')
            const alt = join(dir, entry.name, 'README.md')
            if (existsSync(readme)) {
              found.push({ path: readme, kind, relative: `${entry.name}/SKILL.md` })
            } else if (existsSync(alt)) {
              found.push({ path: alt, kind, relative: `${entry.name}/README.md` })
            }
          }
          continue
        }
        if (RULE_NAMES.has(entry.name) || entry.name.endsWith('.md')) {
          if (entry.name === 'AGENTS.md' || entry.name === 'agents.md' || entry.name === 'CLAUDE.md') {
            found.push({ path: join(dir, entry.name), kind: 'agents', relative: entry.name })
          }
        }
      }
    } catch {
      // missing
    }
  }

  await consider(projectPath, 'agents')
  await consider(join(projectPath, '.dsh', 'skills'), 'dsh-skill')
  await consider(join(projectPath, '.agents', 'skills'), 'skill')
  await consider(join(resolveDshHome(), 'skills'), 'skill')
  return found
}
